export const FIRMWARE_UPDATE_UPDATE_INFO_SAMPLE = {
  'features': {
    'vendor': 'trezor.io',
    'major_version': 2,
    'minor_version': 99,
    'patch_version': 99,
    'bootloader_mode': null,
    'device_id': '851D737A09073D51A26A8EEB',
    'pin_protection': true,
    'passphrase_protection': null,
    'language': 'zh_hk',
    'label': 'UnionKey Touch',
    'initialized': true,
    'revision': 'fccbac81cef7877e6e3b761677ff0d83808380ad',
    'bootloader_hash': null,
    'imported': null,
    'unlocked': false,
    '_passphrase_cached': null,
    'firmware_present': null,
    'needs_backup': null,
    'flags': null,
    'model': 'T',
    'fw_major': null,
    'fw_minor': null,
    'fw_patch': null,
    'fw_vendor': null,
    'unfinished_backup': null,
    'no_backup': null,
    'recovery_mode': null,
    'capabilities': [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    'sd_card_present': true,
    'sd_protection': null,
    'wipe_code_protection': null,
    'session_id':
      '47d8463911f0354f4dc1fa45d403984c43a921926f04bd7f6581c52e6973bd2d',
    'passphrase_always_on_device': null,
    'auto_lock_delay_ms': null,
    'display_rotation': null,
    'experimental_features': null,
    'offset': null,
    'ble_name': 'Touch 3F3B',
    'ble_ver': '2.1.0',
    'ble_enable': true,
    'se_enable': null,
    'se_ver': null,
    'backup_only': null,
    'onekey_version': '4.9.0',
    'onekey_serial': null,
    'bootloader_version': '2.4.9',
    'serial_no': 'TC01WBD202207290844270000046',
    'spi_flash': null,
    'initstates': null,
    'NFT_voucher': null,
    'cpu_info': null,
    'pre_firmware': null,
    'coin_switch': null,
    'build_id':
      '746f7563682e342e392e302d537461626c652d303431302d66636362616338',
    'boardloader_version': '1.0.0',
    'busy': false,
    'onekey_device_type': 'TOUCH',
    'onekey_se_type': 'SE608A',
    'onekey_board_version': '1.0.0',
    'onekey_board_hash': null,
    'onekey_boot_version': '2.4.9',
    'onekey_boot_hash': null,
    'onekey_se01_version': null,
    'onekey_se01_hash': null,
    'onekey_se01_build_id': null,
    'onekey_firmware_version': '4.9.0',
    'onekey_firmware_hash': null,
    'onekey_firmware_build_id': null,
    'onekey_serial_no': 'TC01WBD202207290844270000046',
    'onekey_boot_build_id': null,
    'onekey_ble_name': 'Touch 3F3B',
    'onekey_ble_version': '2.1.0',
    'onekey_ble_build_id': null,
    'onekey_ble_hash': null,
    'onekey_se02_version': null,
    'onekey_se03_version': null,
    'onekey_se04_version': null,
  },
  'deviceType': 'touch',
  'deviceName': 'UnionKey Touch',
  'deviceUUID': 'TC01WBD202207290844270000046',
  'hasUpgrade': true,
  'isBootloaderMode': false,
  'updateInfos': {
    'firmware': {
      'hasUpgrade': true,
      'hasUpgradeForce': false,
      'fromVersion': '4.9.0',
      'toVersion': '4.9.1',
      'releasePayload': {
        'status': 'outdated',
        'changelog': [
          {
            'zh-CN':
              '### ✨ 新功能\r\n- 支持 Manta, Neurai 以及 Nervos 网络\r\n- 支持 LNURL Auth 授权签名\r\n- 支持在设备信息中，查看固件版本号\r\n- 新增在 Celestia 网络下的精度展示\r\n\r\n### 🐞 问题修复\r\n- 修复在 Astar 网络下，查看转账数据卡死的问题\r\n- 修复在闪电网络下，签名信息页面文案缺失的问题\r\n- 修复在核对助记词过程中异常退出，再次进入未触发校验PIN码及退出锁屏失效的问题\r\n\r\n### 💎 改进\r\n- 优化在 Sui 网络下，分包处理签名数据的逻辑\r\n- 优化在 BTC 网络下的签名交易过程中，OP_RETURN 可展示原文\r\n- 优化在波卡网络下，将支持展示更多的签名信息细节\r\n',
            'en-US':
              '### ✨ New Features\r\n- Support for Manta, Neurai, and Nervos networks.\r\n- Support for LNURL Auth authorization signing.\r\n- Ability to view firmware version in device information.\r\n- New precision display under the Celestia network.\r\n\r\n### 🐞 Bug Fixes\r\n- Fixed a freeze when viewing transfer data on the Astar network.\r\n- Fixed missing text on the signature information page on the Lightning network.\r\n- Fixed an issue where re-entering the app after an abnormal exit during recovery phrase verification did not trigger PIN verification and the lock screen was ineffective.\r\n\r\n### 💎 Improvements\r\n- Optimized packet handling logic for signing data on the Sui network.\r\n- Enhanced the display of original text in OP_RETURN during signing transactions on the BTC network.\r\n- Improved the display of detailed signature information on the Polkadot network.\r\n',
          },
        ],
        'release': {
          'required': false,
          'version': [4, 9, 1],
          'bootloaderResource':
            'https://web.unionkey.io/hardware/touch/bootloader/v2.4.9/bootloader.2.4.9-Stable-0807-3e033eb.signed.bin',
          'bootloaderVersion': [2, 4, 8],
          'fullResource':
            'https://web.unionkey.io/hardware/touch/resource/res-4.9.0.zip',
          'fullResourceRange': ['3.5.0', '4.0.0'],
          'resource':
            'https://web.unionkey.io/hardware/touch/resource/resource-4.0.0-4.9.0.zip',
          'url':
            'https://web.unionkey.io/hardware/touch/firmware/v4.9.0/touch.4.9.0-Stable-0410-fccbac8.signed.bin',
          'fingerprint': '',
          'changelog': {
            'zh-CN':
              '### ✨ 新功能\r\n- 支持 Manta, Neurai 以及 Nervos 网络\r\n- 支持 LNURL Auth 授权签名\r\n- 支持在设备信息中，查看固件版本号\r\n- 新增在 Celestia 网络下的精度展示\r\n\r\n### 🐞 问题修复\r\n- 修复在 Astar 网络下，查看转账数据卡死的问题\r\n- 修复在闪电网络下，签名信息页面文案缺失的问题\r\n- 修复在核对助记词过程中异常退出，再次进入未触发校验PIN码及退出锁屏失效的问题\r\n\r\n### 💎 改进\r\n- 优化在 Sui 网络下，分包处理签名数据的逻辑\r\n- 优化在 BTC 网络下的签名交易过程中，OP_RETURN 可展示原文\r\n- 优化在波卡网络下，将支持展示更多的签名信息细节\r\n',
            'en-US':
              '### ✨ New Features\r\n- Support for Manta, Neurai, and Nervos networks.\r\n- Support for LNURL Auth authorization signing.\r\n- Ability to view firmware version in device information.\r\n- New precision display under the Celestia network.\r\n\r\n### 🐞 Bug Fixes\r\n- Fixed a freeze when viewing transfer data on the Astar network.\r\n- Fixed missing text on the signature information page on the Lightning network.\r\n- Fixed an issue where re-entering the app after an abnormal exit during recovery phrase verification did not trigger PIN verification and the lock screen was ineffective.\r\n\r\n### 💎 Improvements\r\n- Optimized packet handling logic for signing data on the Sui network.\r\n- Enhanced the display of original text in OP_RETURN during signing transactions on the BTC network.\r\n- Improved the display of detailed signature information on the Polkadot network.\r\n',
          },
        },
        'bootloaderMode': false,
        'features': {
          'vendor': 'trezor.io',
          'major_version': 2,
          'minor_version': 99,
          'patch_version': 99,
          'bootloader_mode': null,
          'device_id': '851D737A09073D51A26A8EEB',
          'pin_protection': true,
          'passphrase_protection': null,
          'language': 'zh_hk',
          'label': 'UnionKey Touch',
          'initialized': true,
          'revision': 'fccbac81cef7877e6e3b761677ff0d83808380ad',
          'bootloader_hash': null,
          'imported': null,
          'unlocked': false,
          '_passphrase_cached': null,
          'firmware_present': null,
          'needs_backup': null,
          'flags': null,
          'model': 'T',
          'fw_major': null,
          'fw_minor': null,
          'fw_patch': null,
          'fw_vendor': null,
          'unfinished_backup': null,
          'no_backup': null,
          'recovery_mode': null,
          'capabilities': [
            1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17,
          ],
          'sd_card_present': true,
          'sd_protection': null,
          'wipe_code_protection': null,
          'session_id':
            '47d8463911f0354f4dc1fa45d403984c43a921926f04bd7f6581c52e6973bd2d',
          'passphrase_always_on_device': null,
          'auto_lock_delay_ms': null,
          'display_rotation': null,
          'experimental_features': null,
          'offset': null,
          'ble_name': 'Touch 3F3B',
          'ble_ver': '2.1.0',
          'ble_enable': true,
          'se_enable': null,
          'se_ver': null,
          'backup_only': null,
          'onekey_version': '4.9.0',
          'onekey_serial': null,
          'bootloader_version': '2.4.9',
          'serial_no': 'TC01WBD202207290844270000046',
          'spi_flash': null,
          'initstates': null,
          'NFT_voucher': null,
          'cpu_info': null,
          'pre_firmware': null,
          'coin_switch': null,
          'build_id':
            '746f7563682e342e392e302d537461626c652d303431302d66636362616338',
          'boardloader_version': '1.0.0',
          'busy': false,
          'onekey_device_type': 'TOUCH',
          'onekey_se_type': 'SE608A',
          'onekey_board_version': '1.0.0',
          'onekey_board_hash': null,
          'onekey_boot_version': '2.4.9',
          'onekey_boot_hash': null,
          'onekey_se01_version': null,
          'onekey_se01_hash': null,
          'onekey_se01_build_id': null,
          'onekey_firmware_version': '4.9.0',
          'onekey_firmware_hash': null,
          'onekey_firmware_build_id': null,
          'onekey_serial_no': 'TC01WBD202207290844270000046',
          'onekey_boot_build_id': null,
          'onekey_ble_name': 'Touch 3F3B',
          'onekey_ble_version': '2.1.0',
          'onekey_ble_build_id': null,
          'onekey_ble_hash': null,
          'onekey_se02_version': null,
          'onekey_se03_version': null,
          'onekey_se04_version': null,
        },
      },
      'changelog': {
        'zh-CN':
          '### ✨ 新功能\r\n- 支持 Manta, Neurai 以及 Nervos 网络\r\n- 支持 LNURL Auth 授权签名\r\n- 支持在设备信息中，查看固件版本号\r\n- 新增在 Celestia 网络下的精度展示\r\n\r\n### 🐞 问题修复\r\n- 修复在 Astar 网络下，查看转账数据卡死的问题\r\n- 修复在闪电网络下，签名信息页面文案缺失的问题\r\n- 修复在核对助记词过程中异常退出，再次进入未触发校验PIN码及退出锁屏失效的问题\r\n\r\n### 💎 改进\r\n- 优化在 Sui 网络下，分包处理签名数据的逻辑\r\n- 优化在 BTC 网络下的签名交易过程中，OP_RETURN 可展示原文\r\n- 优化在波卡网络下，将支持展示更多的签名信息细节\r\n',
        'en-US':
          '### ✨ New Features\r\n- Support for Manta, Neurai, and Nervos networks.\r\n- Support for LNURL Auth authorization signing.',
      },
      'firmwareType': 'firmware',
    },
    'ble': {
      'hasUpgrade': true,
      'hasUpgradeForce': false,
      'fromVersion': '2.1.0',
      'toVersion': '2.1.1',
      'releasePayload': {
        'status': 'outdated',
        'changelog': [
          {
            'zh-CN':
              '### 🐞 问题修复\r\n- 充电电量显示问题\r\n- 关闭蓝牙后，能够正确关机\r\n',
            'en-US':
              '### 🐞 Bug Fixes\r\n- Fixed charging power display problem\r\n- After turning off bluetooth, it can shut down properly\r\n',
          },
        ],
        'release': {
          'required': false,
          'version': [2, 1, 1],
          'webUpdate':
            'https://common.unionkey.io/hw/touch/2.1.0/touch_ble_signed-2022-1102_2.1.0.bin',
          'fingerprint': '',
          'changelog': {
            'zh-CN':
              '### 🐞 问题修复\r\n- 充电电量显示问题\r\n- 关闭蓝牙后，能够正确关机\r\n',
            'en-US':
              '### 🐞 Bug Fixes\r\n- Fixed charging power display problem\r\n- After turning off bluetooth, it can shut down properly\r\n',
          },
        },
        'bootloaderMode': false,
        'features': {
          'vendor': 'trezor.io',
          'major_version': 2,
          'minor_version': 99,
          'patch_version': 99,
          'bootloader_mode': null,
          'device_id': '851D737A09073D51A26A8EEB',
          'pin_protection': true,
          'passphrase_protection': null,
          'language': 'zh_hk',
          'label': 'UnionKey Touch',
          'initialized': true,
          'revision': 'fccbac81cef7877e6e3b761677ff0d83808380ad',
          'bootloader_hash': null,
          'imported': null,
          'unlocked': false,
          '_passphrase_cached': null,
          'firmware_present': null,
          'needs_backup': null,
          'flags': null,
          'model': 'T',
          'fw_major': null,
          'fw_minor': null,
          'fw_patch': null,
          'fw_vendor': null,
          'unfinished_backup': null,
          'no_backup': null,
          'recovery_mode': null,
          'capabilities': [
            1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17,
          ],
          'sd_card_present': true,
          'sd_protection': null,
          'wipe_code_protection': null,
          'session_id':
            '47d8463911f0354f4dc1fa45d403984c43a921926f04bd7f6581c52e6973bd2d',
          'passphrase_always_on_device': null,
          'auto_lock_delay_ms': null,
          'display_rotation': null,
          'experimental_features': null,
          'offset': null,
          'ble_name': 'Touch 3F3B',
          'ble_ver': '2.1.0',
          'ble_enable': true,
          'se_enable': null,
          'se_ver': null,
          'backup_only': null,
          'onekey_version': '4.9.0',
          'onekey_serial': null,
          'bootloader_version': '2.4.9',
          'serial_no': 'TC01WBD202207290844270000046',
          'spi_flash': null,
          'initstates': null,
          'NFT_voucher': null,
          'cpu_info': null,
          'pre_firmware': null,
          'coin_switch': null,
          'build_id':
            '746f7563682e342e392e302d537461626c652d303431302d66636362616338',
          'boardloader_version': '1.0.0',
          'busy': false,
          'onekey_device_type': 'TOUCH',
          'onekey_se_type': 'SE608A',
          'onekey_board_version': '1.0.0',
          'onekey_board_hash': null,
          'onekey_boot_version': '2.4.9',
          'onekey_boot_hash': null,
          'onekey_se01_version': null,
          'onekey_se01_hash': null,
          'onekey_se01_build_id': null,
          'onekey_firmware_version': '4.9.0',
          'onekey_firmware_hash': null,
          'onekey_firmware_build_id': null,
          'onekey_serial_no': 'TC01WBD202207290844270000046',
          'onekey_boot_build_id': null,
          'onekey_ble_name': 'Touch 3F3B',
          'onekey_ble_version': '2.1.0',
          'onekey_ble_build_id': null,
          'onekey_ble_hash': null,
          'onekey_se02_version': null,
          'onekey_se03_version': null,
          'onekey_se04_version': null,
        },
      },
      'changelog': {
        'zh-CN':
          '### 🐞 问题修复\r\n- 充电电量显示问题\r\n- 关闭蓝牙后，能够正确关机\r\n',
        'en-US':
          '### 🐞 Bug Fixes\r\n- Fixed charging power display problem\r\n- After turning off bluetooth, it can shut down properly\r\n',
      },
      'firmwareType': 'ble',
    },
    'bootloader': {
      'hasUpgrade': true,
      'hasUpgradeForce': false,
      'fromVersion': '2.4.9',
      'toVersion': '2.4.8',
      'releasePayload': {
        'status': 'valid',
        'changelog': [
          {
            'zh-CN':
              '### ✨ 新功能\r\n- 支持 Manta, Neurai 以及 Nervos 网络\r\n- 支持 LNURL Auth 授权签名\r\n- 支持在设备信息中，查看固件版本号\r\n- 新增在 Celestia 网络下的精度展示\r\n\r\n### 🐞 问题修复\r\n- 修复在 Astar 网络下，查看转账数据卡死的问题\r\n- 修复在闪电网络下，签名信息页面文案缺失的问题\r\n- 修复在核对助记词过程中异常退出，再次进入未触发校验PIN码及退出锁屏失效的问题\r\n\r\n### 💎 改进\r\n- 优化在 Sui 网络下，分包处理签名数据的逻辑\r\n- 优化在 BTC 网络下的签名交易过程中，OP_RETURN 可展示原文\r\n- 优化在波卡网络下，将支持展示更多的签名信息细节\r\n',
            'en-US':
              '### ✨ New Features\r\n- Support for Manta, Neurai, and Nervos networks.\r\n- Support for LNURL Auth authorization signing.\r\n- Ability to view firmware version in device information.\r\n- New precision display under the Celestia network.\r\n\r\n### 🐞 Bug Fixes\r\n- Fixed a freeze when viewing transfer data on the Astar network.\r\n- Fixed missing text on the signature information page on the Lightning network.\r\n- Fixed an issue where re-entering the app after an abnormal exit during recovery phrase verification did not trigger PIN verification and the lock screen was ineffective.\r\n\r\n### 💎 Improvements\r\n- Optimized packet handling logic for signing data on the Sui network.\r\n- Enhanced the display of original text in OP_RETURN during signing transactions on the BTC network.\r\n- Improved the display of detailed signature information on the Polkadot network.\r\n',
          },
        ],
        'release': {
          'required': false,
          'version': [4, 9, 1],
          'bootloaderResource':
            'https://web.unionkey.io/hardware/touch/bootloader/v2.4.9/bootloader.2.4.9-Stable-0807-3e033eb.signed.bin',
          'bootloaderVersion': [2, 4, 8],
          'fullResource':
            'https://web.unionkey.io/hardware/touch/resource/res-4.9.0.zip',
          'fullResourceRange': ['3.5.0', '4.0.0'],
          'resource':
            'https://web.unionkey.io/hardware/touch/resource/resource-4.0.0-4.9.0.zip',
          'url':
            'https://web.unionkey.io/hardware/touch/firmware/v4.9.0/touch.4.9.0-Stable-0410-fccbac8.signed.bin',
          'fingerprint': '',
          'changelog': {
            'zh-CN':
              '### ✨ 新功能\r\n- 支持 Manta, Neurai 以及 Nervos 网络\r\n- 支持 LNURL Auth 授权签名\r\n- 支持在设备信息中，查看固件版本号\r\n- 新增在 Celestia 网络下的精度展示\r\n\r\n### 🐞 问题修复\r\n- 修复在 Astar 网络下，查看转账数据卡死的问题\r\n- 修复在闪电网络下，签名信息页面文案缺失的问题\r\n- 修复在核对助记词过程中异常退出，再次进入未触发校验PIN码及退出锁屏失效的问题\r\n\r\n### 💎 改进\r\n- 优化在 Sui 网络下，分包处理签名数据的逻辑\r\n- 优化在 BTC 网络下的签名交易过程中，OP_RETURN 可展示原文\r\n- 优化在波卡网络下，将支持展示更多的签名信息细节\r\n',
            'en-US':
              '### ✨ New Features\r\n- Support for Manta, Neurai, and Nervos networks.\r\n- Support for LNURL Auth authorization signing.\r\n- Ability to view firmware version in device information.\r\n- New precision display under the Celestia network.\r\n\r\n### 🐞 Bug Fixes\r\n- Fixed a freeze when viewing transfer data on the Astar network.\r\n- Fixed missing text on the signature information page on the Lightning network.\r\n- Fixed an issue where re-entering the app after an abnormal exit during recovery phrase verification did not trigger PIN verification and the lock screen was ineffective.\r\n\r\n### 💎 Improvements\r\n- Optimized packet handling logic for signing data on the Sui network.\r\n- Enhanced the display of original text in OP_RETURN during signing transactions on the BTC network.\r\n- Improved the display of detailed signature information on the Polkadot network.\r\n',
          },
        },
        'bootloaderMode': false,
        'shouldUpdate': false,
      },
      'changelog': {
        'zh-CN': '### 🐞 问题修复\r\n- xxxxx',
        'en-US': '### 🐞 Bug Fixes\r\n- xxxx\r\n',
      },
      'firmwareType': 'bootloader',
    },
    'bridge': {
      'shouldUpdate': false,
      'status': 'valid',
      'releaseVersion': '2.2.0',
    },
  },
} as const;
